### ISSUE TITLE
PHP 5.5: Error `Strict Standards: Only variables should be assigned by reference`

### ISSUE THREAD

**Issue by Volker-E** [bueltge/Remove-Comments-Absolutely#20]
Hi!
With `WP_Debug` set to true, remove-comments-absolute.php throws the error **Strict Standards: Only variables should be assigned by reference** at line 326:

    $translations = &get_translations_for_domain( $domain );

Removing the ampersand would solve that issue under PHP 5.5, but I don't know how versions < 5.4 would react.

**Comment by Volker-E** [comment]
Why are you closing it? I didn't send a pull request, because I'm unsure (and don't have the expertise) if removing the ampersand wouldn't introduce regressions in PHP < 5.5.
But in the current code status the problem would stay on.

**Comment by bueltge** [comment]
@Volker-E I think the error is not exists, no problem in tests. Maybe you have new feedback I will reopen and fixed the problem. But currently I can't find the same error.

**Comment by bueltge** [comment]
Can you describe, how I can retrace the error message.

**Comment by oviliz** [comment]
I believe you have to visit the admin side of the plugin/template in order to see the error.

**Comment by bueltge** [comment]
I can't retrace this error. The code from the issue is not inside the plugin, maybe a other problems is inside. But I haven't no error on all pages and the error log. Maybe you have mor information, that I can retrace the problem?

**Comment by oviliz** [comment]
Hi @bueltge ,
sorry for not being precise.

I am using a template which is generating the same error when debugging and accessing the template back-end panel. Looking for a solution I find this post and made my suggestion, but I'm not actually using your plugin even similar code may be part of my template.

**Comment by bueltge** [comment]
Hello @oviliz 
Thanks a lot. I see forward for new feedback thats helps me to resolve the problem.

**Comment by barryceelen** [comment]
Old issue but did some digging: the error came from ```$translations = &get_translations_for_domain( $domain );``` which was added to `wp-includes/l10n.php` in WordPress version 2.8. The ampersand was [removed in version 3.5](https://github.com/WordPress/WordPress/commit/3c09c18) for this reason.
