### ISSUE TITLE
PHP 5.5 Strict Standards issue

### ISSUE THREAD

**Issue by senlin** [bueltge/Remove-Comments-Absolutely#24]
I'm getting a Strict Standards notice:
`Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method Remove_Comments_Absolute::get_object() should not be called statically in /path/wp-includes/plugin.php on line 496`

**Comment by bueltge** [comment]
Do you have check with the last version of this repository? The method `get_object()` is static and I'm wondering about the error message. Thanks for your feedback.

**Comment by senlin** [comment]
Thanks Frank, your updated version 1.2.2 solves the issue.
