### ISSUE TITLE
Remove/Hide "Comments are closed" from template

### ISSUE THREAD

**Issue by Neustradamus** [bueltge/Remove-Comments-Absolutely#32]
Can you remove/hide the comments template ("Comments are closed") too?

**Comment by bueltge** [comment]
You can also hide this via css or JS inside the Theme or a custom plugin. I think this is more helpful.
Important for the plugin is, that we create a exit, with or without message it is a string.

**Comment by bueltge** [comment]
Thanks @barryceelen now I understand the issue much better. I think this should run also faster, the the `gettext` hook is slowly.

**Comment by Neustradamus** [comment]
Thanks :)

**Comment by bueltge** [comment]
Welcome.
