### ISSUE TITLE
Plans to publish plugin on the WordPress plugins repository?

### ISSUE THREAD

**Issue by tyrann0us** [bueltge/Remove-Comments-Absolutely#38]
Do you have plans to push this plugin to the WordPress plugin repository (https://wordpress.org/plugins/disable-comments/)?

Thanks!

**Comment by bueltge** [comment]
Hi. Currently no, the effort is much higher, support is a important thing on wp.org 
I have to much plugins on the public repository, lot of support questions. 
Maybe you see better positive points to publish on this site?

**Comment by tyrann0us** [comment]
Thanks for clarification. I'll close this issue.

**Comment by bueltge** [comment]
Welcome.
