### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by nlemoine** [bueltge/remove-comments-absolutely#40]
Hi,

Would you consider adding your plugin to packagist? I'm using composer to handle plugins and Remove-Comments-Absolutely isn't registered in any repository. Have to manually declare this:
```json
    {
      "type": "vcs",
      "url": "https://github.com/bueltge/Remove-Comments-Absolutely"
    }
```
in my composer.json.

**Comment by nlemoine** [comment]
Hello @bueltge,

This is working great. Thanks for considering the request and make it happen so fast 👍

**Comment by bueltge** [comment]
Really welcome.
