### ISSUE TITLE
Comments Meta Box from edit-post is not removed

### ISSUE THREAD

**Issue by ludwig-gramberg** [bueltge/remove-comments-absolutely#44]
In Wordpress 5.5.3 I can't find a way to remove the comments meta box except removing it with jquery.

```
function remove_post_comments() {
        ?>
        <script type="text/javascript">
            //<![CDATA[
            jQuery( document ).ready( function() {
                jQuery('#adv-settings label[for="commentsdiv-hide"]').remove();
                jQuery('#commentsdiv').remove();
            } );
            //]]>
        </script>
        <?php
    }
add_action( 'admin_footer-post.php', 'remove_post_comments' );
```

**Comment by bueltge** [comment]
@ludwig-gramberg Is Gutenberg active or do you use the Classic Editor? I will check them and maybe send any update.

**Comment by ludwig-gramberg** [comment]
@bueltge classic editor

**Comment by bueltge** [comment]
Problems should be solved, without the enhancement via JS, that makes other topics, problems. Would you test the current master branch, a replacement of the main PHP file is enough. After them, I will release a new version.

**Comment by bueltge** [comment]
@ludwig-gramberg You will find a pre-release here - https://github.com/bueltge/remove-comments-absolutely/releases/tag/1.5.4 Please test this version, maybe you miss a topic. Thanks for your feedback, so I will release this verison.

**Comment by ludwig-gramberg** [comment]
It works! 👍 Thank you!

**Comment by bueltge** [comment]
Thanks for your feedback @ludwig-gramberg The new release is live, tagged.
