### ISSUE TITLE
Error on empty search result pages

### ISSUE THREAD

**Issue by faahim** [bueltge/remove-comments-absolutely#64]
Hello @bueltge 👋 

Great work on the plugin!

We've just discovered a scenario where the plugin throws the following error/warning on the empty search result pages:

```
Error displayed: E_NOTICE - Trying to get property 'name' of non-object
File: [site_path]/app/mu-plugins/remove-comments-absolutely/remove-comments-absolute.php
```

And

```
Error displayed: E_NOTICE - Trying to get property 'term_id' of non-object
File: [site_path]/app/mu-plugins/remove-comments-absolutely/remove-comments-absolute.php
```

I've tracked down the issue and submitted #63 
Please let me know if it can be merged or if any change is required.

Thanks!

**Comment by bueltge** [comment]
Thanks for the PR to fix them.

**Comment by faahim** [comment]
Thanks a ton for the super quick response! 😄
